# commit to be tagged for the new release
commit = "HEAD"

project_name = "talos-sbc-helios64"
github_repo = "blmhemu/talos-sbc-helios64"
match_deps = "^github.com/(blmhemu/[a-zA-Z0-9-]+)$"

# previous = -
# pre_release = true

# [notes]
